server:
  port: 8083

warehouse:
  kafka:
    message-group-name: warehouse-group
    order-created-topic: hw30.order.created
    payment-succeeded-topic: hw30.payment.succeeded
    payment-rejected-topic: hw30.payment.rejected
    warehouse-product-reserved-topic: hw30.warehouse.product.reserved
    warehouse-product-reservation-rejected-topic: hw30.warehouse.product.reservation.rejected
    delivery-rejected-topic: hw30.delivery.rejected

spring:
  application:
    name: warehouse

  datasource:
    url: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/db_otus_30
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      leak-detection-threshold: 10000
  flyway:
    enabled: true
    schemas: warehouse_scheme

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    template:
      default-topic: my-topic
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org:
      apache:
        kafka: OFF



